# Generated by Django 5.0.3 on 2024-04-07 10:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bi_menu", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
