# Generated by Django 5.0.3 on 2024-04-08 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bi_menu", "0002_menu_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="parent_menu",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submenus",
                to="bi_menu.menu",
            ),
        ),
    ]
