# Generated by Django 5.0.4 on 2024-10-30 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authusers", "0003_alter_role_codename_alter_role_viewname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role_fk",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="role_users",
                to="authusers.role",
            ),
        ),
    ]
